bifrost_bridge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls') ),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('process_scada.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

process_scada/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt
from . import views
urlpatterns = [
    path('file/upload/', views.FileUploadView.as_view() ,name = 'file_upload'),
    path('file/upload/success/', TemplateView.as_view(template_name='file_upload_success.html'), name='success'),

    path("parameter/", views.ParameterListView.as_view(), name="view_parameter"),
    path("parameter/add/", views.ParameterCreationView.as_view(), name="add_parameter"),
    path("parameter/<pk>/update/", views.ParameterUpdationView.as_view(), name="update_parameter"),
    path("parameter/<pk>/delete/", views.ParameterDeleteView.as_view(), name="delete_parameter"),

    path("diagnosis/", views.DiagnosisListView.as_view(), name="view_diagnosis"),
    path("diagnosis/add/", views.DiagnosisCreationView.as_view(), name="add_diagnosis"),
    path("diagnosis/<pk>/update/", views.DiagnosisUpdationView.as_view(), name="update_diagnosis"),
    path("diagnosis/<pk>/delete/", views.DiagnosisDeleteView.as_view(), name="delete_diagnosis"),

    path("production/", views.ProductionListView.as_view(), name="view_production"),
    path("production/add/", views.ProductionCreationView.as_view(), name="add_production"),
    path("production/<pk>/update/", views.ProductionUpdationView.as_view(), name="update_production"),
    path("production/<pk>/delete/", views.ProductionDeleteView.as_view(), name="delete_production"),

    path("change/", views.ChangeListView.as_view(), name="view_change"),
    path("change/add/", views.ChangeCreationView.as_view(), name="add_change"),
    path("change/<pk>/update/", views.ChangeUpdationView.as_view(), name="update_change"),
    path("change/<pk>/delete/", views.ChangeDeleteView.as_view(), name="delete_change"),

    path('api/', csrf_exempt(views.ApiEndpoint.as_view()),name='api'),

    path("batch/", views.BatchListView.as_view(), name="view_batch"),
    path("batch/add/", views.BatchCreationView.as_view(), name="add_batch"),
    path("batch/<pk>/update/", views.BatchUpadteView.as_view(), name="update_batch"),
    path("batch/<pk>/delete/", views.BatchDeleteView.as_view(), name="delete_batch"),
    path("batch/<pk>/", views.BatchDetailView.as_view(), name='detail_batch'),

    path("product/", views.ProductListView.as_view(), name="view_product"),
    path("product/add/", views.ProductCreationView.as_view(), name="add_product"),
    path("product/<pk>/update/", views.ProductUpadteView.as_view(), name="update_product"),
    path("product/<pk>/delete/", views.ProductDeleteView.as_view(), name="delete_product"),
    path("product/<pk>/", views.ProductDetailView.as_view(), name="detail_product")
]

process_scada/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils.timezone import now

# Create your models here.
class File(models.Model):
    file =  models.FileField( upload_to='reports/', max_length=100)

class Product(models.Model):
    name = models.CharField(primary_key=True, max_length=50)
    def __str__(self):
        return f'{self.name}'
    
class Batch(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    batch_no = models.CharField(primary_key=True,max_length=20)

    def __str__(self):
        return f'{self.product}  {self.batch_no}'

class Parameter(models.Model):
    sno = models.PositiveSmallIntegerField(primary_key=True, verbose_name='Serial No.',help_text='Enter the Serial No.')
    name = models.CharField(max_length=200,verbose_name='Parameter Name', help_text='Enter the Parameter Name')
    value = models.CharField(max_length=200,verbose_name='Parameter Value', help_text='Enter the Parameter Value')
    description = models.TextField(blank=True,null=True,max_length=1000, verbose_name='Parameter Description', help_text='Enter the Parameter Description')

    class Meta:
        ordering = ['sno'] 

    def __str__(self):
        return f'{self.sno}  {self.name}  {self.value}'
    
    def get_absolute_url(self):
        return reverse_lazy('view_parameter')

class Diagnosis(models.Model):

    DIAGNOSIS_FILTERS = (
        ('S', 'S'),
        ('W', 'W'),
        ('D', 'D'),
    )
    timestamp = models.DateTimeField(default=now,verbose_name='Event Time', primary_key=True)
    diagnosis_filter = models.CharField(max_length=5, choices=DIAGNOSIS_FILTERS,help_text='Choose the diagnosis filter')    
    error_code = models.IntegerField(help_text='Enter the Error Code',verbose_name='Error Code')
    details = models.TextField(blank=True, null=True, verbose_name="Details", help_text='Enter the Details of Diagnosis')
    batch = models.ForeignKey(Batch, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f'{self.timestamp}  {self.diagnosis_filter}  {self.error_code}'

    def get_absolute_url(self):
        return reverse_lazy('view_diagnosis')

class Production(models.Model):

    TYPE_CHOICES = [
        ('P','P'),
        ('E','E'),
        
    ]

    time = models.DateTimeField(default=now,verbose_name='Date and Time', help_text='Enter the date and time for the event', primary_key=True)
    types = models.CharField(max_length=5, choices = TYPE_CHOICES,verbose_name='Type', help_text='Enter the type')
    quantity  = models.PositiveIntegerField(help_text='Enter the production quantity in x1000', verbose_name='Quantity')
    comp_mmv =  models.CharField(max_length=10,help_text='Enter the Compression force M,MV', verbose_name='Compression Force ( M MV)')
    comp_srel = models.CharField(max_length=10,help_text = 'Enter compression force Srel %', verbose_name='Compression force( SRel %)')
    comp_pmv = models.CharField(max_length=10,help_text='Enter the compression force P MV', verbose_name='Compression Force ( P MV) ')
    batch = models.ForeignKey(Batch, on_delete=models.DO_NOTHING)

    class Meta:
        ordering = ['time']

    def __str__(self):
        return f'{self.time}  {self.types}  {self.quantity}  {self.comp_mmv}   {self.comp_srel}  {self.comp_pmv}'
    def get_absolute_url(self):
        return reverse_lazy("view_production")
    
class Change(models.Model):
    time = models.DateTimeField(verbose_name= 'Date and Time', primary_key=True)
    operation = models.CharField(max_length=30, verbose_name='Operation Type', help_text='Enter the operation type')
    description = models.TextField(max_length=200, verbose_name='Description',help_text='Enter Operation Description')
    batch = models.ForeignKey(Batch, on_delete=models.DO_NOTHING)
    
    def __str__(self):
        return f'{self.time}  {self.operation}  {self.description}'
    
    def get_absolute_url(self):
        return reverse_lazy('view_change')
    

process_scada/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from . import forms
from . import models
from time import sleep
from .utils.pdf_extractor import read_report
from json import dumps,loads
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from pprint import pprint

# Create your views here.
class FileUploadView(LoginRequiredMixin , generic.FormView):
    template_name = 'generic_form.html'
    form_class = forms.FileUploadForm
    success_url = 'success'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        print('form received')
        if form.is_valid():
            print('form valid ')
            pdf_file = self.request.FILES['file']
            print('its a change form')
            data_to_db = read_report(pdf_file)
            batch = data_to_db['batch']
            product = data_to_db['product']
            print(product)
            product_model, created = models.Product.objects.get_or_create(name=product)
            batch_model, created = models.Batch.objects.get_or_create(product=product_model, batch_no=batch)
            product_form = forms.ProductForm(data={'name':product}) 
            for row in data_to_db['change']:
                final_data = {
                    'time': row[0],
                    'operation' : row[1],
                    'description' : row[2],
                    'batch': batch_model.pk,
                }
                print(final_data)
                print()
                change_form = forms.ChangeForm(data=final_data) 
                if change_form.is_valid():
                    print('change form is valid ')
                    change_form.save()
                else:
                    print(change_form.__dict__)
                    print('change form is invalid ')

            print('diagnosis is doing ')
            for row in data_to_db['diagnosis']:
                final_data = {
                    'timestamp': row[0],
                    'diagnosis_filter' : row[1],
                    'error_code' : row[2],
                    'details': row[3],
                    'batch': batch_model.pk,
                }
                diagnosis_form = forms.DiagnosisForm(data=final_data) 
                if diagnosis_form.is_valid():
                    print('diagnosis form is valid ')
                    diagnosis_form.save()
                else:
                    print('diagnosis form is invalid ')
            print('production started')
            for row in data_to_db['production']:
                final_data = {
                    'time': row[0],
                    'types': row[1],
                    'quantity': row[2],
                    'comp_mmv': row[3],
                    'comp_srel': row[4],
                    'comp_pmv': row[5],
                    'batch': batch_model.pk,
                }
                production_form = forms.ProductionForm(data=final_data) 
                if production_form.is_valid():
                    print('production form is valid ')
                    production_form.save()
                else:
                    print('production form is invalid ')


            
            return self.form_valid(form, **kwargs)
        else:
            print('form invalid')
            return self.form_invalid(form, **kwargs)

    def form_invalid(self, form, **kwargs):
        context = self.get_context_data(**kwargs)
        context['form'] = form
        return self.render_to_response(context)

    # def form_valid(self, form, **kwargs):
    #     context = self.get_context_data(**kwargs)
    #     context['form'] = form
    #     return self.render_to_response(context)


class ParameterListView(LoginRequiredMixin, generic.ListView):
    model = models.Parameter
    template_name = 'parameter_list.html'

class ParameterCreationView(LoginRequiredMixin, generic.CreateView):
    form_class =  forms.ParameterForm
    template_name = 'generic_form.html'

class ParameterUpdationView(LoginRequiredMixin, generic.UpdateView):
    model = models.Parameter
    form_class = forms.ParameterForm
    template_name = 'generic_form.html'

class ParameterDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = models.Parameter
    template_name = 'delete_confirm.html'
    success_url =reverse_lazy( 'view_parameter')


class DiagnosisListView(LoginRequiredMixin, generic.ListView):
    model = models.Diagnosis
    template_name = 'diagnosis_list.html'

class DiagnosisCreationView(LoginRequiredMixin, generic.CreateView):
    form_class =  forms.DiagnosisForm
    template_name = 'generic_form.html'

class DiagnosisUpdationView(LoginRequiredMixin, generic.UpdateView):
    model = models.Diagnosis
    form_class = forms.DiagnosisForm
    template_name = 'generic_form.html'

class DiagnosisDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = models.Diagnosis
    template_name = 'delete_confirm.html'
    success_url = reverse_lazy('view_diagnosis')


class ProductionListView(LoginRequiredMixin, generic.ListView):
    model = models.Production
    template_name = 'production_list.html'

class ProductionCreationView(LoginRequiredMixin,generic.CreateView):
    form_class = forms.ProductionForm
    template_name = 'generic_form.html'

class ProductionUpdationView(LoginRequiredMixin,generic.UpdateView):
    model = models.Production
    form_class = forms.ProductionForm
    template_name = 'generic_form.html'

class ProductionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = models.Production
    template_name = 'delete_confirm.html'
    success_url = reverse_lazy('view_production')


class ChangeListView(LoginRequiredMixin, generic.ListView):
    model = models.Change
    template_name = 'change_list.html'

class ChangeCreationView(LoginRequiredMixin, generic.CreateView):
    form_class = forms.ChangeForm
    template_name = 'generic_form.html'

class ChangeUpdationView(LoginRequiredMixin, generic.UpdateView):
    model = models.Change
    form_class = forms.ChangeForm
    template_name = 'generic_form.html'

class ChangeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = models.Change
    template_name = 'delete_confirm.html'
    success_url = reverse_lazy('view_change')

class ApiEndpoint(generic.View):
    def get(self,request):
        return HttpResponse('fuck u ')
    def post(self,request,*args, **kwargs):
        data = loads(self.request.body)
        change_data = data['change']
        diagnosis_data = data['diagnosis']
        batch = data['batch']
        product = data['product']
        print(product)
        print(data['production'])
        product_model, created = models.Product.objects.get_or_create(name=product)
        batch_model, created = models.Batch.objects.get_or_create(product=product_model, batch_no=batch)
        product_form = forms.ProductForm(data={'name':product})
        print(product_form.__dict__)
        print('going to start ')
        for row in change_data:
            final_data = {
                'batch':batch_model.pk,
                'time': row[0],
                'operation' : row[1],
                'description' : row[2],
            }
            change_form = forms.ChangeForm(data=final_data) 
            if change_form.is_valid():
                print('change form is valid ')
                change_form.save()
            else:
                print('change form is invalid ')

        for row in diagnosis_data:
            print(row)
            final_data = {
                'batch':batch_model.pk,
                'timestamp': row[0],
                'diagnosis_filter' : row[1],
                'error_code' : row[2],
                'details': row[3],
            }
            diagnosis_form = forms.DiagnosisForm(data=final_data) 
            if diagnosis_form.is_valid():
                print('diagnosis form is valid ')
                diagnosis_form.save()
            else:
                print('diagnosis form is invalid ')
            
        for row in data['production']:
            print(row)
            final_data = {
                'time': row[0],
                'types': row[1],
                'quantity': row[2],
                'comp_mmv': row[3],
                'comp_srel': row[4],
                'comp_pmv': row[5],
                'batch': batch_model.pk,
            }
            production_form = forms.ProductionForm(data=final_data) 
            print(production_form.__dict__)
            if production_form.is_valid():
                print('production form is valid ')
                production_form.save()
            else:
                print('production form is invalid ')

            

        
        return HttpResponse('success')

class BatchListView(LoginRequiredMixin, generic.ListView):
    model = models.Batch
    template_name = 'batch_list.html'

class BatchCreationView(LoginRequiredMixin, generic.CreateView):
    form_class =  forms.BatchForm
    template_name = 'generic_form.html'

class BatchUpadteView(LoginRequiredMixin, generic.UpdateView):
    model = models.Batch
    form_class = forms.BatchForm
    template_name = 'generic_form.html'

class BatchDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = models.Batch
    template_name = 'delete_confirm.html'
    success_url = reverse_lazy('view_batch')

class BatchDetailView(LoginRequiredMixin,generic.DetailView):
    model = models.Batch
    template_name = 'batch_detail.html'





class ProductListView(LoginRequiredMixin, generic.ListView):
    model = models.Product
    template_name = 'product_list.html'

class ProductCreationView(LoginRequiredMixin, generic.CreateView):
    form_class =  forms.ProductForm
    template_name = 'generic_form.html'

class ProductUpadteView(LoginRequiredMixin, generic.UpdateView):
    model = models.Product

process_scada/templates/batch_detail.html
{% extends 'base.html' %}

{% block content %}

<br>
<div class="container h-100 mt-3">
<h1 class='text-center jumbotron'>Batch Details</h1>
<hr>
<div class='table-responsive'>
<hr>
<a class="btn btn-warning" data-toggle="collapse" href="#prod" role="button" aria-expanded="false" aria-controls="prod" style="width: 100%;">
    <h3>Production Report</h3>
</a>
<div class="collapse" id="prod">
<table class="table-striped table col-12 table-hover " >
<thead>
<th>Timestamp</th>
<th>Types</th>
<th>Quantity</th>
<th>Compression Force <br>MMV</th>
<th>Compression Force <br>S-Rel %</th>
<th>Compression Force <br>PMV</th>
<th>Edit</th>
</thead>
<tbody >
{% for production in batch.production_set.all %}
<tr>
    <td>{{production.time}}</td>
    <td>{{production.types}}</td>
    <td>{{production.quantity}}</td>
    <td>{{production.comp_mmv}}</td>
    <td>{{production.comp_srel}}</td>
    <td>{{production.comp_pmv}}</td>
    <td><a class="btn btn-primary" href="{% url 'update_production' production.pk %}"><i class="fa fa-pen"></i></a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
<hr>
<a class="btn btn-secondary" data-toggle="collapse" href="#change" role="button" aria-expanded="false" aria-controls="change" style="width: 100%;">
    <h3>Change Report</h3>
</a>
<div class="collapse" id="change">
<table class="table-striped table col-12 table-hover ">
<thead>
<th>Time</th>
<th>Operation</th>
<th>Description</th>
<th>Edit</th>
</thead>
<tbody>
{% for change in batch.change_set.all %}
<tr>
    <td>{{change.time}}</td>
    <td>{{change.operation}}</td>
    <td>{{change.description}}</td>
    <td><a class="btn btn-primary" href="{% url 'update_change' change.pk %}"><i class="fa fa-pen"></i></a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
<hr>
<a class="btn btn-success" data-toggle="collapse" href="#diagno" role="button" aria-expanded="false" aria-controls="diagno" style="width: 100%;">
    <h3>Diagnosis Report</h3>
</a>
<table class="table-striped table col-12 table-hover collapse" id="diagno">
<thead>
<th>Timestamp</th>
<th>Error Code</th>
<th>Filter</th>
<th>Details</th>
<th>Edit</th>
</thead>
{% for diagnosis in batch.diagnosis_set.all %}
<tr>
    <td>{{diagnosis.timestamp}}</td>
    <td>{{diagnosis.error_code}}</td>
    <td>{{diagnosis.diagnosis_filter}}</td>
    <td>{{diagnosis.details}}</td>
    <td><a class="btn btn-primary" href="{% url 'update_diagnosis' diagnosis.pk %}"><i class="fa fa-pen"></i></a></td>
</tr>
{% endfor %}
</table>
</div>
</div>

{% endblock content %}
{% block script %}

{% endblock script %}

process_scada/templates/batch_list.html
{% extends 'base_list.html' %}

{% block table %}
<thead>
    <th>Batch Number</th>
    <th>Product</th>
    <th>Visit</th>
    <th>Edit</th>
    <th>Delete</th>
</thead>
<tbody>

{% for batch in object_list %}
<tr>
        <td>{{batch.batch_no}}</td>
        <td>{{batch.product}}</td>
        <td><a href="{% url 'detail_batch' batch.pk%} " class='btn btn-success'>
        <i class="fas fa-search    "></i>
        </a></td>
        <td><a class="btn btn-primary" href="{% url 'update_batch' batch.pk %}"><span class="fa fa-pen"></span></a></td>
        <td><button class="btn btn-danger" onclick="deleteBatch('{% url 'delete_batch' batch.pk %}')"><span class="fa fa-trash"></span></button></td>
</tr>
{% endfor %}
</tbody>

<script>
   function deleteBatch(url)
    {
        console.log(url);
        $.ajax({
            type: "GET",
            url: url,
            success: function(response)
            {
                showModal({'head':'Delete Batch ?','body': response, 'url':url });
            }
        });
    }
</script>

{% endblock table %}

process_scada/templates/change_list.html
{% extends 'base_list.html' %}
{% block table %}

<thead>
    <th>Timestamp</th>
    <th>Operation</th>
    <th>Description</th>
    <th>Edit</th>
    <th>Delete</th>
</thead>
<tbody>

<tr>
{% for change in object_list %}
    <td>{{change.time}}</td>
    <td>{{change.operation}}</td>
    <td>{{change.description}}</td>
    <td><a class="btn btn-primary" href="{% url 'update_change' change.pk %}"><span class="fa fa-pen"></span></a></td>
    <td><button class="btn btn-danger" onclick="deleteChange('{% url 'delete_change' change.pk %}')"><span class="fa fa-trash"></span></button></td>
</tr>
{% endfor %}
</tbody>

<script>
   function deleteChange(url)
    {
        console.log(url);
        $.ajax({
            type: "GET",
            url: url,
            success: function(response)
            {
                showModal({'head':'Delete Diagnosis ?','body': response, 'url':url });
            }
        });
    }
</script>

{% endblock table %}

process_scada/templates/diagnosis_list.html
{% extends 'base_list.html' %}

{% block table %}
<thead>
    <th>Timestamp</th>
    <th>Filter</th>
    <th>Error Code</th>
    <th>Details</th>
    <th>Edit</th>
    <th>Delete</th>
</thead>
<tbody>

<tr>
{% for diagnosis in object_list %}
    <td>{{diagnosis.timestamp}}</td>
    <td>{{diagnosis.diagnosis_filter}}</td>
    <td>{{diagnosis.error_code}}</td>
    <td>{{diagnosis.details}}</td>
    <td><a class="btn btn-primary" href="{% url 'update_diagnosis' diagnosis.pk %}"><span class="fa fa-pen"></span></a></td>
    <td><button class="btn btn-danger" onclick="deleteDiagnosis('{% url 'delete_diagnosis' diagnosis.pk %}')"><span class="fa fa-trash"></span></button></td>
</tr>
{% endfor %}
</tbody>

<script>
   function deleteDiagnosis(url)
    {
        console.log(url);
        $.ajax({
            type: "GET",
            url: url,
            success: function(response)
            {
                showModal({'head':'Delete Diagnosis ?','body': response, 'url':url });
            }
        });
    }
</script>

{% endblock table %}

process_scada/templates/file_upload_success.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron text-center">
    <h1 class="display-3">success</h1>
    <p class="lead">File Uploaded! Processing Now.</p>
    <hr class="my-2">
    <p>Check your Mail later for the processed files information. </p>
    <p class="lead">
        <a class="btn btn-success btn-lg" href="{% url 'home'%}" role="button"> 
        <i class="fa fa-home" aria-hidden="true"></i>
            Back Home 
        </a>
        <a class="btn btn-warning btn-lg" href="{% url 'file_upload'%}" role="button">
        <i class="fa fa-backward" aria-hidden="true"></i>
            Another Upload 
         </a>
    </p>
</div>

{% endblock content %}

process_scada/templates/parameter_list.html
{% extends 'base_list.html' %}

{% block table %}
<thead>
    <th>S.No.</th>
    <th>Parameter Name</th>
    <th>Parameter Description</th>
    <th>Parameter Value</th>
    <th>Edit</th>
    <th>Delete</th>
</thead>
<tbody>

<tr>
{% for parameter in object_list %}
    <td>{{parameter.sno}}</td>
    <td>{{parameter.name}}</td>
    <td>{{parameter.description |truncatewords:30 }} </td>
    <td>{{parameter.value}}</td>
    <td><a class="btn btn-primary" href="{% url 'update_parameter' parameter.pk %}"><span class="fa fa-pen"></span></a></td>
    <td><button class="btn btn-danger" onclick="deleteParameter('{% url 'delete_parameter' parameter.pk %}')"><span class="fa fa-trash"></span></button></td>
</tr>
{% endfor %}
</tbody>

<script>
   function deleteParameter(url)
    {
        console.log(url);
        $.ajax({
            type: "GET",
            url: url,
            success: function(response)
            {
                showModal({'head':'Delete Parameter ?','body': response, 'url':url });
            }
        });
    }
</script>

{% endblock table %}

process_scada/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container h-100 mt-3">
    <h1 class='text-center jumbotron'>Product Details</h1>
    <hr>
    <div class='table-responsive'>
        <hr>
            <h3>Production Report</h3>
            <table class="table-striped table col-12 table-hover ">
                <thead>
                    <th>Batch No.</th>
                    <th>View</th>
                    <th>Edit</th>
                </thead>
                <tbody>
                    {% for batch in product.batch_set.all %}
                    <tr>
                        <td>{{batch.batch_no}}</td>
                        <td><a href="{% url 'detail_batch' batch.pk%}" class="btn btn-success"> <i class="fa fa-eye" aria-hidden="true"></i> </a></td>
                        <td><a class="btn btn-primary" href="{% url 'update_batch' batch.pk %}"><i class="fa fa-pen"></i></a></td>
                    </tr>

                        {% endfor %}
                </tbody>
            </table>
    </div>
</div>
    {% endblock content %}

process_scada/templates/product_list.html
{% extends 'base_list.html' %}

{% block table %}
<thead>
    <th>Product</th>
    <th>Visit</th>
    <th>Edit</th>
    <th>Delete</th>
</thead>
<tbody>

{% for product in object_list %}
<tr>
        <td>{{product.name}}</td>
        <td><a href="{% url 'detail_product' product.pk%} " class='btn btn-success'>
        <i class="fas fa-search   "></i>
        </a></td>
        <td><a class="btn btn-primary" href="{% url 'update_product' product.pk %}"><span class="fa fa-pen"></span></a></td>
        <td><button class="btn btn-danger" onclick="deleteProduct('{% url 'delete_product' product.pk %}')"><span class="fa fa-trash"></span></button></td>
</tr>
{% endfor %}
</tbody>

<script>
   function deleteProduct(url)
    {
        console.log(url);
        $.ajax({
            type: "GET",
            url: url,
            success: function(response)
            {
                showModal({'head':'Delete Batch ?','body': response, 'url':url });
            }
        });
    }
</script>

{% endblock table %}

process_scada/templates/production_list.html
{% extends 'base_list.html' %}

{% block table %}
<thead>
    <th>Timestamp</th>
    <th>Type</th>
    <th>Prod. x1000</th>
    <th>MMV</th>
    <th>SRel</th>
    <th>PMV</th>
    <th>Edit</th>
    <th>Delete</th>
</thead>
<tbody>

<tr>
{% for production in object_list %}
    <td>{{production.time}}</td>
    <td>{{production.types}}</td>
    <td>{{production.quantity}}</td>
    <td>{{production.comp_mmv}}</td>
    <td>{{production.comp_srel}}</td>
    <td>{{production.comp_pmv}}</td>
    <td><a class="btn btn-primary" href="{% url 'update_production' production.pk %}"><span class="fa fa-pen"></span></a></td>
    <td><button class="btn btn-danger" onclick="deleteProduction('{% url 'delete_production' production.pk %}')"><span class="fa fa-trash"></span></button></td>
</tr>
{% endfor %}
</tbody>

<script>
   function deleteProduction(url)
    {
        console.log(url);
        $.ajax({
            type: "GET",
            url: url,
            success: function(response)
            {
                showModal({'head':'Delete Diagnosis ?','body': response, 'url':url });
            }
        });
    }
</script>

{% endblock table %}